CREATE DATABASE IF NOT EXISTS openedx DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'openedx'@'%' IDENTIFIED BY 'CHANGE_ME';
GRANT ALL PRIVILEGES ON openedx.* TO 'openedx'@'%';
FLUSH PRIVILEGES;
